FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


WORKDIR /code-back

COPY apps/backend/requirements/dev.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt

COPY apps/backend /code-back/


EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]